### ISSUE TITLE
Have to check array with longer suffixes first.

### ISSUE THREAD

**Issue by dmarman** [NaturalNode/natural#399]
https://github.com/NaturalNode/natural/blob/8071055f103f2d9fead395c5b823e0b247fb13a7/lib/natural/stemmers/porter_stemmer_es.js#L196

You have to check first the upper array and then this one: `Array('en', 'es', 'éis', 'emos')`

**Comment by dmarman** [comment]
Sorry but this is not an improvement. It is a bad implementation of the original algorithm.

**Comment by Hugo-ter-Doest** [comment]
Yes, that is exactly what I mean by labelling it with improvement. The current implementation requires improvement.

Hugo

**Comment by Hugo-ter-Doest** [comment]
So, if I exchange the two arrays that are being tested, then it works as expected for Spanish? I am checking because I don't know what I am doing (in Spanish) if I make the change.

Hugo

**Comment by Hugo-ter-Doest** [comment]
I saw that there is no unit test for the Porter stemmer for Spanish. I wrote a quick test following the Italian test. Applied it to the [Snowball vocabulary](http://snowball.tartarus.org/algorithms/spanish/diffs.txt) and it gives more than 2476 errors (of the 28390 entries). See the [log](https://gist.github.com/Hugo-ter-Doest/ee4b529bb30594ee86cb11e8f2abe981).

Anyone knows what is going on? Is the stemmer for Spanish not finished?

Hugo

**Comment by dmarman** [comment]
The Porter stemmer for Spanish has three issues I already pointed out. That's why it is giving so many errors.

I implemented it properly here:
https://github.com/dmarman/lorca/blob/master/src/stemmer.js

to solve this issue the code should look like something like this:


```
if (wordAfter2a == wordAfter1) {
                if((suf = this.endsInArr(rvText, ['arían', 'arías', 'arán', 'arás', 'aríais', 'aría', 'aréis',
                                                    'aríamos', 'aremos', 'ará', 'aré', 'erían', 'erías', 'erán',
                                                    'erás', 'eríais', 'ería', 'eréis', 'eríamos', 'eremos', 'erá',
                                                    'eré', 'irían', 'irías', 'irán', 'irás', 'iríais', 'iría', 'iréis',
                                                    'iríamos', 'iremos', 'irá', 'iré', 'aba', 'ada', 'ida', 'ía', 'ara',
                                                    'iera', 'ad', 'ed', 'id', 'ase', 'iese', 'aste', 'iste', 'an',
                                                    'aban', 'ían', 'aran', 'ieran', 'asen', 'iesen', 'aron', 'ieron',
                                                    'ado', 'ido', 'ando', 'iendo', 'ió', 'ar', 'er', 'ir', 'as', 'abas',
                                                    'adas', 'idas', 'ías', 'aras', 'ieras', 'ases', 'ieses', 'ís', 'áis',
                                                    'abais', 'íais', 'arais', 'ierais', '  aseis', 'ieseis', 'asteis',
                                                    'isteis', 'ados', 'idos', 'amos', 'ábamos', 'íamos', 'imos', 'áramos',
                                                    'iéramos', 'iésemos', 'ásemos'])) != '')
                {
                    word = word.slice(0, -suf.length);
                }else if((suf = this.endsInArr(rvText, ['en', 'es', 'éis', 'emos'])) != '') {
					word = word.slice(0, -suf.length);
                    if(this.endsIn(word, 'gu')){
                        word = word.slice(0, -1);
					}
				}
            }
```

Sorry that I don't do it myself, I just don't have the time now...

**Comment by Hugo-ter-Doest** [comment]
Ok, thanks for the guidance, I will check it out and make a PR later this weekend.

Hugo

**Comment by Hugo-ter-Doest** [comment]
Did the test against the snowball vocabulary, and it almost works...One error remains:

**Comment by dmarman** [comment]
vocabulary is wrong, you cannot have a word with two accents. 
Although I don't know why it is replacing properly the first one from méxico, but not the second one from querétar..

did you got any other error?

Domingo

**Comment by Hugo-ter-Doest** [comment]
No, that's the only error left.

Hugo

**Comment by dmarman** [comment]
I would then check why querétar is left with the accent... The regex for that looks good for me.
I implemented in the function in a different way though:

```
removeAccent(word)
    {
        var accentedVowels = ['á', 'é', 'í', 'ó', 'ú'];
        var vowels = ['a', 'e', 'i', 'o', 'u'];

        for(var i in accentedVowels){
            word = word.replace(accentedVowels[i], vowels[i]);
        }

        return word;
    }
```

**Comment by Hugo-ter-Doest** [comment]
Sorry, I didn't state that explicitly, but I'm already using your implementation that you posted in the other issue [#400](https://github.com/NaturalNode/natural/issues/400):
https://github.com/dmarman/lorca/blob/master/src/stemmer.js
and that leaves us with this one error. 

Hugo

**Comment by dmarman** [comment]
Ok :) Remove it from the list. It's a wierd word and bad formed.

**Comment by Hugo-ter-Doest** [comment]
I committed the new stemmer to the repo including a unit test with test data: [commit](https://github.com/NaturalNode/natural/commit/dc66a6140f7eb9a57d3022dd957fb6887871a96c)

Thanks for your input!

Hugo

**Comment by dmarman** [comment]
Nice Job! 🎉 

If you want, you can add to this repro this syllaber I did for Spanish:
https://github.com/dmarman/lorca/blob/master/src/syllabler.js

and this sentiment analysis:
https://github.com/dmarman/lorca/blob/master/src/sentimenter.js
This one needs some improvement, but it kinda works...

**Comment by Hugo-ter-Doest** [comment]
I think sentiment analysis would be a great addition to the library. We already had a request for such functionality. See [here](https://github.com/NaturalNode/natural/issues/334). Did you use an existing algorithm for this? And can we generalize this to other languages in a straightforward way? If it can be used as a framework for other languages, where language files are kept separate that would be great. I see that you are using a number of vocabularies to configure the sentimenter. Could you elaborate a bit on the algorithm? Or do you have some documentation?

Hugo
